-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then
  vim.cmd("highlight clear")
end
vim.g.colors_name = "kanagawa-kai"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "Constant" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@constant.macro", { link = "Define" })
hi(0, "@constructor", { fg = "#e5a942" })
hi(0, "@constructor.lua", { fg = "#d9a600" })
hi(0, "@exception", { bold = true, fg = "#d5695c" })
hi(0, "@function.builtin", { link = "Special" })
hi(0, "@function.macro", { link = "Macro" })
hi(0, "@keyword.luap", { link = "@string.regex" })
hi(0, "@keyword.operator", { bold = true, fg = "#d5695c" })
hi(0, "@keyword.return", { fg = "#d5695c", italic = true })
hi(0, "@lsp.mod.readonly", { link = "Constant" })
hi(0, "@lsp.mod.typeHint", { link = "Type" })
hi(0, "@lsp.type.builtinConstant", { link = "@constant.builtin" })
hi(0, "@lsp.type.class", { link = "Structure" })
hi(0, "@lsp.type.comment", {})
hi(0, "@lsp.type.decorator", { link = "Function" })
hi(0, "@lsp.type.enum", { link = "Structure" })
hi(0, "@lsp.type.enumMember", { link = "Constant" })
hi(0, "@lsp.type.function", { link = "Function" })
hi(0, "@lsp.type.interface", { link = "Structure" })
hi(0, "@lsp.type.macro", { link = "Macro" })
hi(0, "@lsp.type.magicFunction", { link = "@function.builtin" })
hi(0, "@lsp.type.method", { link = "@method" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "Identifier" })
hi(0, "@lsp.type.selfParameter", { link = "@variable.builtin" })
hi(0, "@lsp.type.struct", { link = "Structure" })
hi(0, "@lsp.type.type", { link = "Type" })
hi(0, "@lsp.type.typeParameter", { link = "Typedef" })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.function.builtin", { link = "@function.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.function.readonly", { bold = true, fg = "#a5b172" })
hi(0, "@lsp.typemod.keyword.documentation", { link = "Special" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.controlFlow", { link = "@exception" })
hi(0, "@lsp.typemod.operator.injected", { link = "Operator" })
hi(0, "@lsp.typemod.string.injected", { link = "String" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "Special" })
hi(0, "@lsp.typemod.variable.global", { link = "Constant" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@lsp.typemod.variable.static", { link = "Constant" })
hi(0, "@parameter", { fg = "#afa58b" })
hi(0, "@punctuation.bracket", { fg = "#a79984" })
hi(0, "@punctuation.delimiter", { fg = "#a79984" })
hi(0, "@punctuation.special", { fg = "#e5a942" })
hi(0, "@string.escape", { bold = true, fg = "#d5695c" })
hi(0, "@string.regex", { fg = "#d5695c" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@symbol", { fg = "#d3ad78" })
hi(0, "@tag.attribute", { fg = "#d3ad78" })
hi(0, "@tag.delimiter", { fg = "#a79984" })
hi(0, "@text.danger", { bg = "#8c8c8c", bold = true, fg = "#c3cdb2" })
hi(0, "@text.diff.add", { fg = "#88904d" })
hi(0, "@text.diff.delete", { fg = "#d5695c" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.environment", { link = "Keyword" })
hi(0, "@text.environment.name", { link = "String" })
hi(0, "@text.literal", { link = "String" })
hi(0, "@text.math", { link = "Constant" })
hi(0, "@text.note", { bg = "#979797", bold = true, fg = "#0c3649" })
hi(0, "@text.quote", { link = "@parameter" })
hi(0, "@text.reference", { link = "Identifier" })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.title", { link = "Function" })
hi(0, "@text.todo", { link = "Todo" })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@text.uri", { link = "Underlined" })
hi(0, "@text.warning", { bg = "#c5c5c5", bold = true, fg = "#0c3649" })
hi(0, "@type.definition", { link = "Typedef" })
hi(0, "@variable", { fg = "#c3cdb2" })
hi(0, "@variable.builtin", { fg = "#d5695c", italic = true })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { bold = true, fg = "#c48b6d" })
hi(0, "Character", { link = "String" })
hi(0, "CmpCompletion", { link = "Pmenu" })
hi(0, "CmpCompletionBorder", { bg = "#3d3d3d", fg = "#115363" })
hi(0, "CmpCompletionSbar", { link = "PmenuSbar" })
hi(0, "CmpCompletionSel", { bg = "#575757" })
hi(0, "CmpCompletionThumb", { link = "PmenuThumb" })
hi(0, "CmpDocumentation", { link = "NormalFloat" })
hi(0, "CmpDocumentationBorder", { link = "FloatBorder" })
hi(0, "CmpItemAbbr", { fg = "#e8d3ab" })
hi(0, "CmpItemAbbrDefault", { fg = "#e8d3ab" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#757d64", strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#757d64" })
hi(0, "CmpItemAbbrMatch", { fg = "#a5b172" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#e8d3ab" })
hi(0, "CmpItemAbbrMatchFuzzy", { link = "CmpItemAbbrMatch" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#e8d3ab" })
hi(0, "CmpItemKind", { fg = "#e5a942" })
hi(0, "CmpItemKindClass", { link = "Type" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColor", { fg = "#e5a942" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { link = "Constant" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { link = "@constructor" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindCopilot", { fg = "#a9b700" })
hi(0, "CmpItemKindDefault", { fg = "#e5a942" })
hi(0, "CmpItemKindEnum", { link = "Type" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { link = "Constant" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { fg = "#e5a942" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { link = "@field" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { link = "Directory" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { link = "Directory" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { link = "Type" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { link = "@keyword" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { link = "Function" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { link = "@include" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { link = "Operator" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { link = "@property" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { link = "Type" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { fg = "#e5a942" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { link = "Type" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { fg = "#e8d3ab" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { link = "Type" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { fg = "#e5a942" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { link = "String" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { fg = "#d8bb7e" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#757d64" })
hi(0, "CmpItemMenuDefault", { fg = "#e8d3ab" })
hi(0, "ColorColumn", { bg = "#333333" })
hi(0, "Comment", { fg = "#757d64", italic = true })
hi(0, "Conceal", { bold = true, fg = "#71877c" })
hi(0, "Constant", { fg = "#c48b6d" })
hi(0, "CurSearch", { bg = "#575757", bold = true, fg = "#c3cdb2" })
hi(0, "Cursor", { bg = "#d6d6d6", fg = "#1d1414" })
hi(0, "CursorColumn", { link = "CursorLine" })
hi(0, "CursorIM", { link = "Cursor" })
hi(0, "CursorLine", { bg = "#444444" })
hi(0, "CursorLineNr", { bg = "#333333", bold = true, fg = "#ff9b48" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#d3ad78" })
hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
hi(0, "DapUIBreakpointsInfo", { fg = "#548a91" })
hi(0, "DapUIBreakpointsPath", { link = "Directory" })
hi(0, "DapUIDecoration", { fg = "#d8bb7e" })
hi(0, "DapUIFloatBorder", { fg = "#d8bb7e" })
hi(0, "DapUILineNumber", { fg = "#e5a942" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#e5a942" })
hi(0, "DapUINormalNC", { bg = "#232323", fg = "#c3cdb2" })
hi(0, "DapUIPlayPause", { fg = "#979764" })
hi(0, "DapUIPlayPauseNC", { fg = "#e7ef00" })
hi(0, "DapUIRestart", { fg = "#979764" })
hi(0, "DapUIRestartNC", { fg = "#e7ef00" })
hi(0, "DapUIScope", { link = "Special" })
hi(0, "DapUISource", { fg = "#d5695c" })
hi(0, "DapUIStepBack", { fg = "#e5a942" })
hi(0, "DapUIStepBackNC", { fg = "#00f7c4" })
hi(0, "DapUIStepInto", { fg = "#e5a942" })
hi(0, "DapUIStepIntoNC", { fg = "#00f7c4" })
hi(0, "DapUIStepOut", { fg = "#e5a942" })
hi(0, "DapUIStepOutNC", { fg = "#00f7c4" })
hi(0, "DapUIStepOver", { fg = "#e5a942" })
hi(0, "DapUIStepOverNC", { fg = "#00f7c4" })
hi(0, "DapUIStop", { fg = "#d5695c" })
hi(0, "DapUIStopNC", { fg = "#d5695c" })
hi(0, "DapUIStoppedThread", { fg = "#e5a942" })
hi(0, "DapUIThread", { fg = "#d3ad78" })
hi(0, "DapUIType", { link = "Type" })
hi(0, "DapUIUnavailable", { fg = "#757d64" })
hi(0, "DapUIUnavailableNC", { fg = "#424242" })
hi(0, "DapUIWatchesEmpty", { fg = "#d5695c" })
hi(0, "DapUIWatchesError", { fg = "#d5695c" })
hi(0, "DapUIWatchesValue", { fg = "#d3ad78" })
hi(0, "DapUIWinSelect", { bold = true, ctermfg = 14, fg = "#00f7c4" })
hi(0, "DashboardCenter", { fg = "#d3ad78" })
hi(0, "DashboardDesc", { fg = "#d3ad78" })
hi(0, "DashboardFooter", { fg = "#757d64" })
hi(0, "DashboardHeader", { fg = "#d5695c" })
hi(0, "DashboardIcon", { fg = "#71877c" })
hi(0, "DashboardKey", { fg = "#e5a942" })
hi(0, "DashboardShortCut", { fg = "#e5a942" })
hi(0, "Delimiter", { fg = "#a79984" })
hi(0, "DiagnosticError", { fg = "#d5695c" })
hi(0, "DiagnosticHint", { fg = "#699970" })
hi(0, "DiagnosticInfo", { fg = "#548a91" })
hi(0, "DiagnosticOk", { fg = "#b7b23d" })
hi(0, "DiagnosticSignError", { bg = "#333333", fg = "#d5695c" })
hi(0, "DiagnosticSignHint", { bg = "#333333", fg = "#699970" })
hi(0, "DiagnosticSignInfo", { bg = "#333333", fg = "#548a91" })
hi(0, "DiagnosticSignWarn", { bg = "#333333", fg = "#d9a600" })
hi(0, "DiagnosticUnderlineError", { sp = "#d5695c", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#6a9589", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#658594", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#d9a600", undercurl = true })
hi(0, "DiagnosticWarn", { fg = "#d9a600" })
hi(0, "DiffAdd", { bg = "#3c3c3c" })
hi(0, "DiffChange", { bg = "#333333" })
hi(0, "DiffDelete", { bg = "#3b3b3b", fg = "#d5695c" })
hi(0, "DiffText", { bg = "#515151" })
hi(0, "Directory", { fg = "#a5b172" })
hi(0, "EndOfBuffer", { fg = "#1d1414" })
hi(0, "Error", { fg = "#d5695c" })
hi(0, "ErrorMsg", { fg = "#d5695c" })
hi(0, "Exception", { fg = "#d5695c" })
hi(0, "ExtraWhitespace", { bg = "#939393", ctermbg = 9 })
hi(0, "FloatBorder", { fg = "#40587c" })
hi(0, "FloatShadow", { bg = "#000000", blend = 50 })
hi(0, "FloatShadowThrough", { bg = "#000000", blend = 100 })
hi(0, "FloatTitle", { bold = true, fg = "#71877c" })
hi(0, "FloatermBorder", { bg = "#232323", fg = "#40587c" })
hi(0, "FoldColumn", { bg = "#333333", fg = "#685d50" })
hi(0, "Folded", { bg = "#333333", fg = "#71877c" })
hi(0, "Function", { fg = "#a5b172" })
hi(0, "GitSignsAdd", { bg = "#333333", fg = "#88904d" })
hi(0, "GitSignsAddInline", { reverse = true })
hi(0, "GitSignsAddLn", { bg = "#3c3c3c" })
hi(0, "GitSignsAddLnInline", { reverse = true })
hi(0, "GitSignsAddNr", { bg = "#333333", fg = "#88904d" })
hi(0, "GitSignsAddPreview", { bg = "#3c3c3c" })
hi(0, "GitSignsChange", { bg = "#333333", fg = "#ed9c4f" })
hi(0, "GitSignsChangeInline", { reverse = true })
hi(0, "GitSignsChangeLn", { bg = "#333333" })
hi(0, "GitSignsChangeLnInline", { reverse = true })
hi(0, "GitSignsChangeNr", { bg = "#333333", fg = "#ed9c4f" })
hi(0, "GitSignsChangedelete", { bg = "#333333", fg = "#ed9c4f" })
hi(0, "GitSignsChangedeleteLn", { bg = "#333333" })
hi(0, "GitSignsChangedeleteNr", { bg = "#333333", fg = "#ed9c4f" })
hi(0, "GitSignsCurrentLineBlame", { fg = "#685d50" })
hi(0, "GitSignsDelete", { bg = "#333333", fg = "#d5695c" })
hi(0, "GitSignsDeleteInline", { reverse = true })
hi(0, "GitSignsDeleteLnInline", { reverse = true })
hi(0, "GitSignsDeleteNr", { bg = "#333333", fg = "#d5695c" })
hi(0, "GitSignsDeletePreview", { bg = "#3b3b3b", fg = "#d5695c" })
hi(0, "GitSignsDeleteVirtLn", { bg = "#3b3b3b", fg = "#d5695c" })
hi(0, "GitSignsDeleteVirtLnInLine", { reverse = true })
hi(0, "GitSignsStagedAdd", { bg = "#333333", fg = "#444926" })
hi(0, "GitSignsStagedAddLn", { bg = "#3c3c3c" })
hi(0, "GitSignsStagedAddNr", { bg = "#333333", fg = "#444926" })
hi(0, "GitSignsStagedChange", { bg = "#333333", fg = "#774d27" })
hi(0, "GitSignsStagedChangeLn", { bg = "#333333" })
hi(0, "GitSignsStagedChangeNr", { bg = "#333333", fg = "#774d27" })
hi(0, "GitSignsStagedChangedelete", { bg = "#333333", fg = "#774d27" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#333333" })
hi(0, "GitSignsStagedChangedeleteNr", { bg = "#333333", fg = "#774d27" })
hi(0, "GitSignsStagedDelete", { bg = "#333333", fg = "#681713" })
hi(0, "GitSignsStagedDeleteNr", { bg = "#333333", fg = "#681713" })
hi(0, "GitSignsStagedTopdelete", { bg = "#333333", fg = "#681713" })
hi(0, "GitSignsStagedTopdeleteNr", { bg = "#333333", fg = "#681713" })
hi(0, "GitSignsTopdelete", { bg = "#333333", fg = "#d5695c" })
hi(0, "GitSignsTopdeleteNr", { bg = "#333333", fg = "#d5695c" })
hi(0, "GitSignsUntracked", { bg = "#333333", fg = "#88904d" })
hi(0, "GitSignsUntrackedLn", { bg = "#3c3c3c" })
hi(0, "GitSignsUntrackedNr", { bg = "#333333", fg = "#88904d" })
hi(0, "GitSignsVirtLnum", { bg = "#3b3b3b", fg = "#d5695c" })
hi(0, "Identifier", { fg = "#d3ad78" })
hi(0, "Ignore", { link = "NonText" })
hi(0, "IlluminatedWordRead", { underline = true })
hi(0, "IlluminatedWordText", { underline = true })
hi(0, "IlluminatedWordWrite", { underline = true })
hi(0, "IncSearch", { bg = "#c5c5c5", fg = "#0c3649" })
hi(0, "IndentBlanklineChar", { fg = "#685d50" })
hi(0, "IndentBlanklineContextChar", { fg = "#71877c" })
hi(0, "IndentBlanklineContextStart", { sp = "#7a8382", underline = true })
hi(0, "IndentBlanklineSpaceChar", { fg = "#685d50" })
hi(0, "IndentBlanklineSpaceCharBlankline", { fg = "#685d50" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#d9a600", italic = true })
hi(0, "LazyProgressTodo", { fg = "#685d50" })
hi(0, "LineNr", { bg = "#333333", fg = "#685d50" })
hi(0, "LspCodeLens", { fg = "#757d64" })
hi(0, "LspInfoBorder", { bold = true, fg = "#d9a600" })
hi(0, "LspInfoFiletype", { fg = "#84a996" })
hi(0, "LspInfoList", { fg = "#a5b172" })
hi(0, "LspInfoTip", { fg = "#757d64", italic = true })
hi(0, "LspInfoTitle", { bold = true, fg = "#a5b172" })
hi(0, "LspReferenceRead", { link = "LspReferenceText" })
hi(0, "LspReferenceText", { bg = "#515151" })
hi(0, "LspReferenceWrite", { bg = "#515151", underline = true })
hi(0, "LspSignatureActiveParameter", { fg = "#ff9b48" })
hi(0, "MasonNormal", { bg = "#191919", fg = "#d8bb7e" })
hi(0, "MatchParen", { bold = true, fg = "#ff9b48" })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "ModeMsg", { bold = true, fg = "#ff9b48" })
hi(0, "MoreMsg", { fg = "#548a91" })
hi(0, "MsgArea", { fg = "#d8bb7e" })
hi(0, "MsgSeparator", { bg = "#191919" })
hi(0, "NeoTreeGitAdded", { fg = "#88904d" })
hi(0, "NeoTreeGitConflict", { fg = "#d5695c" })
hi(0, "NeoTreeGitDeleted", { fg = "#d5695c" })
hi(0, "NeoTreeGitModified", { fg = "#ed9c4f" })
hi(0, "NeoTreeGitStaged", { fg = "#88904d" })
hi(0, "NeoTreeGitUnstaged", { fg = "#ed9c4f" })
hi(0, "NeoTreeGitUntracked", { fg = "#ed9c4f" })
hi(0, "NeoTreeIndentMarker", { link = "NonText" })
hi(0, "NeoTreeModified", { link = "String" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#d3ad78" })
hi(0, "NeoTreeTabActive", { link = "TabLineSel" })
hi(0, "NeoTreeTabInactive", { link = "TabLine" })
hi(0, "NeoTreeTabSeparatorActive", { link = "NeoTreeTabActive" })
hi(0, "NeoTreeTabSeparatorInactive", { link = "NeoTreeTabInactive" })
hi(0, "NeogitDiffAddHighlight", { bg = "#3c3c3c" })
hi(0, "NeogitDiffContextHighlight", { bg = "#333333" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#3b3b3b" })
hi(0, "NeogitHunkHeader", { fg = "#a5b172" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#333333", fg = "#c48b6d" })
hi(0, "NeoscrollHiddenCursor", { blend = 100, reverse = true })
hi(0, "NonText", { fg = "#685d50" })
hi(0, "Normal", { bg = "NONE", fg = "#c3cdb2" })
hi(0, "NormalDark", { bg = "#191919", fg = "#d8bb7e" })
hi(0, "NormalFloat", { fg = "#d8bb7e" })
hi(0, "NormalNC", { bg = "#282828", fg = "#d8bb7e" })
hi(0, "LazyNormal", { link = "NormalNC" })
hi(0, "NotifierContent", { bg = "#232323", fg = "#c3cdb2" })
hi(0, "NotifierContentDim", { fg = "#757d64", italic = true })
hi(0, "NotifierIcon", { bold = true, fg = "#a5b172" })
hi(0, "NotifierTitle", { bold = true, fg = "#a5b172" })
hi(0, "NotifyBackground", { bg = "#232323" })
hi(0, "NotifyDEBUGBorder", { link = "Debug" })
hi(0, "NotifyDEBUGIcon", { link = "Debug" })
hi(0, "NotifyDEBUGTitle", { link = "Debug" })
hi(0, "NotifyERRORBorder", { link = "DiagnosticError" })
hi(0, "NotifyERRORIcon", { link = "DiagnosticError" })
hi(0, "NotifyERRORTitle", { link = "DiagnosticError" })
hi(0, "NotifyHINTBorder", { link = "DiagnosticHint" })
hi(0, "NotifyHINTIcon", { link = "DiagnosticHint" })
hi(0, "NotifyHINTTitle", { link = "DiagnosticHint" })
hi(0, "NotifyINFOBorder", { link = "DiagnosticInfo" })
hi(0, "NotifyINFOIcon", { link = "DiagnosticInfo" })
hi(0, "NotifyINFOTitle", { link = "DiagnosticInfo" })
hi(0, "NotifyTRACEBorder", { link = "Comment" })
hi(0, "NotifyTRACEIcon", { link = "Comment" })
hi(0, "NotifyTRACETitle", { link = "Comment" })
hi(0, "NotifyWARNBorder", { link = "DiagnosticWarn" })
hi(0, "NotifyWARNIcon", { link = "DiagnosticWarn" })
hi(0, "NotifyWARNTitle", { link = "DiagnosticWarn" })
hi(0, "NullLsInfoBorder", { fg = "#d8bb7e" })
hi(0, "NullLsInfoHeader", { bold = true, fg = "#d9a600" })
hi(0, "NullLsInfoSources", { bold = true, fg = "#a5b172" })
hi(0, "NullLsInfoTitle", { fg = "#84a996" })
hi(0, "Number", { fg = "#9494bc" })
hi(0, "NvimInternalError", { bg = "#939393", ctermbg = 9, ctermfg = 9, fg = "#fa2300" })
hi(0, "NvimTreeBookmark", { fg = "#979764" })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#979764" })
hi(0, "NvimTreeFolderIcon", { fg = "#659bba" })
hi(0, "NvimTreeGitDeleted", { fg = "#d5695c" })
hi(0, "NvimTreeGitDirty", { fg = "#ed9c4f" })
hi(0, "NvimTreeGitMerge", { fg = "#f6bc75" })
hi(0, "NvimTreeGitNew", { fg = "#88904d" })
hi(0, "NvimTreeGitRenamed", { fg = "#9494bc" })
hi(0, "NvimTreeGitStaged", { fg = "#88904d" })
hi(0, "NvimTreeImageFile", { fg = "#d5695c" })
hi(0, "NvimTreeIndentMarker", { fg = "#659bba" })
hi(0, "NvimTreeLiveFilterPrefix", { bold = true, fg = "#9494bc" })
hi(0, "NvimTreeLiveFilterValue", { bold = true })
hi(0, "NvimTreeModifiedFile", { fg = "#979764" })
hi(0, "NvimTreeOpenedFile", { fg = "#e5a942", italic = true })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#d3ad78" })
hi(0, "NvimTreeSpecialFile", { fg = "#e5a942" })
hi(0, "NvimTreeSymlink", { link = "Type" })
hi(0, "NvimTreeWindowPicker", { bg = "#282828", bold = true, fg = "#e5a942" })
hi(0, "Operator", { fg = "#d5695c" })
hi(0, "Pmenu", { bg = "#3c3c3c", fg = "#e8d3ab" }) -- MODIFIED
hi(0, "PmenuSbar", { bg = "#3c3c3c" }) -- MODIFIED
hi(0, "PmenuSel", { bg = "#575757" })
hi(0, "PmenuThumb", { bg = "#3c3c3c" })
-- hi(0, "Pmenu", { bg = "#FF0000", fg = "#e8d3ab" }) -- MODIFIED
-- hi(0, "PmenuSbar", { bg = "#00FF00" }) -- MODIFIED
-- hi(0, "PmenuSel", { bg = "#0000FF" })
-- hi(0, "PmenuThumb", { bg = "#AA00FF" })
hi(0, "PreProc", { fg = "#d5695c" })
hi(0, "Question", { link = "MoreMsg" })
hi(0, "QuickFixLine", { bg = "#333333" })
hi(0, "RedrawDebugClear", { bg = "#ffffff", ctermbg = 11 })
hi(0, "RedrawDebugComposed", { bg = "#757575", ctermbg = 10 })
hi(0, "RedrawDebugRecompose", { bg = "#939393", ctermbg = 9 })
hi(0, "Search", { bg = "#575757", fg = "#c3cdb2" })
hi(0, "SignColumn", { bg = "#333333", fg = "#71877c" })
hi(0, "Special", { fg = "#e5a942" })
hi(0, "SpecialKey", { fg = "#71877c" })
hi(0, "SpellBad", { sp = "#d5695c", undercurl = true })
hi(0, "SpellCap", { sp = "#ff9e3b", undercurl = true })
hi(0, "SpellLocal", { sp = "#ff9e3b", undercurl = true })
hi(0, "SpellRare", { sp = "#ff9e3b", undercurl = true })
hi(0, "Statement", { bold = true, fg = "#d9a600" })
hi(0, "StatusLine", { bg = "#191919", fg = "#d8bb7e" })
hi(0, "StatusLineNC", { bg = "#191919", fg = "#685d50" })
hi(0, "String", { fg = "#979764" })
hi(0, "Substitute", { bg = "#818181", fg = "#c3cdb2" })
hi(0, "TSPlaygroundFocus", { bg = "#3d3d3d" })
hi(0, "TSPlaygroundLang", { fg = "#979764" })
hi(0, "TSQueryLinterError", { fg = "#d5695c" })
hi(0, "TabLine", { bg = "#191919", fg = "#71877c" })
hi(0, "TabLineFill", { bg = "#232323" })
hi(0, "TabLineSel", { bg = "#333333", fg = "#d8bb7e" })
hi(0, "TabbyHL_0d0c0c_181616_NONE", { bg = "#232323", fg = "#110a0b" })
hi(0, "TabbyHL_8ba4b0_0d0c0c_NONE", { bg = "#191919", fg = "#7aa9ae" })
hi(0, "TabbyHL_8ba4b0_181616_NONE", { bg = "#232323", fg = "#7aa9ae" })
hi(0, "TabbyHL_8ba4b0_a87b4a_NONE", { bg = "#929292", fg = "#7aa9ae" })
hi(0, "TabbyHL_a87b4a_181616_NONE", { bg = "#232323", fg = "#b5753c" })
hi(0, "TabbyHL_f2e5bf_a87b4a_NONE", { bg = "#929292", fg = "#fde1b8" })
hi(0, "TelescopeBorder", { bg = "#232323", fg = "#40587c" })
hi(0, "TelescopeMatching", { fg = "#e5a942" })
hi(0, "TelescopeMultiIcon", { fg = "#d3ad78" })
hi(0, "TelescopeMultiSelection", { fg = "#84a996" })
hi(0, "TelescopeNormal", { bg = "#232323", fg = "#c3cdb2" })
hi(0, "TelescopePreviewBlock", { fg = "#c48b6d" })
hi(0, "TelescopePreviewBorder", { bg = "#1f1f1f", fg = "#14120c" })
hi(0, "TelescopePreviewCharDev", { fg = "#c48b6d" })
hi(0, "TelescopePreviewDate", { fg = "#a5b172" })
hi(0, "TelescopePreviewDirectory", { fg = "#a5b172" })
hi(0, "TelescopePreviewExecute", { fg = "#979764" })
hi(0, "TelescopePreviewGroup", { fg = "#c48b6d" })
hi(0, "TelescopePreviewHyphen", { fg = "#685d50" })
hi(0, "TelescopePreviewLine", { bg = "#3d3d3d" })
hi(0, "TelescopePreviewLink", { fg = "#e5a942" })
hi(0, "TelescopePreviewMatch", { bg = "#575757", fg = "#c3cdb2" })
hi(0, "TelescopePreviewMessage", { bg = "#1f1f1f" })
hi(0, "TelescopePreviewMessageFillchar", { bg = "#1f1f1f" })
hi(0, "TelescopePreviewNormal", { bg = "#1f1f1f" })
hi(0, "TelescopePreviewPipe", { fg = "#c48b6d" })
hi(0, "TelescopePreviewRead", { fg = "#c48b6d" })
hi(0, "TelescopePreviewSize", { fg = "#979764" })
hi(0, "TelescopePreviewSocket", { bold = true, fg = "#d9a600" })
hi(0, "TelescopePreviewSticky", { fg = "#d9a600", italic = true })
hi(0, "TelescopePreviewTitle", { bold = true, fg = "#71877c" })
hi(0, "TelescopePreviewUser", { fg = "#c48b6d" })
hi(0, "TelescopePreviewWrite", { bold = true, fg = "#d9a600" })
hi(0, "TelescopePromptBorder", { bg = "#333333", fg = "#302424" })
hi(0, "TelescopePromptCounter", { fg = "#685d50" })
hi(0, "TelescopePromptNormal", { bg = "#333333" })
hi(0, "TelescopePromptPrefix", { fg = "#d3ad78" })
hi(0, "TelescopePromptTitle", { bold = true, fg = "#71877c" })
hi(0, "TelescopeResultsBorder", { bg = "#282828", fg = "#201c15" })
hi(0, "TelescopeResultsClass", { link = "Structure" })
hi(0, "TelescopeResultsComment", { fg = "#757d64", italic = true })
hi(0, "TelescopeResultsConstant", { fg = "#c48b6d" })
hi(0, "TelescopeResultsDiffAdd", { bg = "#3c3c3c" })
hi(0, "TelescopeResultsDiffChange", { bg = "#333333" })
hi(0, "TelescopeResultsDiffDelete", { bg = "#3b3b3b", fg = "#d5695c" })
hi(0, "TelescopeResultsDiffUntracked", { fg = "#685d50" })
hi(0, "TelescopeResultsField", { link = "@field" })
hi(0, "TelescopeResultsFunction", { fg = "#a5b172" })
hi(0, "TelescopeResultsIdentifier", { fg = "#d3ad78" })
hi(0, "TelescopeResultsLineNr", { bg = "#333333", fg = "#685d50" })
hi(0, "TelescopeResultsMethod", { link = "Function" })
hi(0, "TelescopeResultsNormal", { bg = "#282828", fg = "#d8bb7e" })
hi(0, "TelescopeResultsNumber", { fg = "#9494bc" })
hi(0, "TelescopeResultsOperator", { fg = "#d5695c" })
hi(0, "TelescopeResultsSpecialComment", { fg = "#e5a942" })
hi(0, "TelescopeResultsStruct", { link = "Structure" })
hi(0, "TelescopeResultsTitle", { bold = true, fg = "#71877c" })
hi(0, "TelescopeResultsVariable", { link = "@variable" })
hi(0, "TelescopeSelection", { link = "CursorLine" })
hi(0, "TelescopeSelectionCaret", { link = "CursorLineNr" })
hi(0, "TelescopeTitle", { bold = true, fg = "#71877c" })
hi(0, "Title", { bold = true, fg = "#a5b172" })
hi(0, "Todo", { bg = "#8c8c8c", bold = true, fg = "#0c3649" })
hi(0, "TreesitterContext", { link = "Folded" })
hi(0, "TreesitterContextBottom", {})
hi(0, "TreesitterContextLineNumber", { bg = "#333333", fg = "#71877c" })
hi(0, "Type", { fg = "#84a996" })
hi(0, "Underlined", { fg = "#e5a942", underline = true })
hi(0, "VertSplit", { link = "WinSeparator" })
hi(0, "Visual", { bg = "#3d3d3d" })
hi(0, "VisualNOS", { link = "Visual" })
hi(0, "WarningMsg", { fg = "#ff9b48" })
hi(0, "Whitespace", { fg = "#685d50" })
hi(0, "WildMenu", { link = "Pmenu" })
hi(0, "WinBar", { fg = "#d8bb7e" })
hi(0, "WinBarNC", { bg = "#1f1f1f", fg = "#d8bb7e" })
hi(0, "WinSeparator", { bg = "#1f1f1f", fg = "#110a0b" })
hi(0, "debugBreakpoint", { bg = "#333333", fg = "#e5a942" })
hi(0, "debugPC", { bg = "#3b3b3b" })
hi(0, "diffAdded", { fg = "#88904d" })
hi(0, "diffChanged", { fg = "#ed9c4f" })
hi(0, "diffDeleted", { fg = "#d5695c" })
hi(0, "diffNewFile", { fg = "#88904d" })
hi(0, "diffOldFile", { fg = "#d5695c" })
hi(0, "diffRemoved", { fg = "#d5695c" })
hi(0, "healthError", { fg = "#d5695c" })
hi(0, "healthSuccess", { fg = "#b7b23d" })
hi(0, "healthWarning", { fg = "#ff9b48" })
hi(0, "lCursor", { link = "Cursor" })
hi(0, "lualine_a_command", { bg = "#9a9a9a", fg = "#1d1414" })
hi(0, "lualine_a_inactive", { bg = "#191919", fg = "#d8bb7e" })
hi(0, "lualine_a_insert", { bg = "#bbbbbb", fg = "#1d1414" })
hi(0, "lualine_a_normal", { bg = "#acacac", fg = "#110a0b" })
hi(0, "lualine_a_replace", { bg = "#a8a8a8", fg = "#1d1414" })
hi(0, "lualine_a_visual", { bg = "#9f9f9f", fg = "#1d1414" })
hi(0, "lualine_b_command", { bg = "#232323", fg = "#d5695c" })
hi(0, "lualine_b_inactive", { bg = "#191919", bold = true, fg = "#d8bb7e" })
hi(0, "lualine_b_insert", { bg = "#232323", fg = "#b7b23d" })
hi(0, "lualine_b_normal", { bg = "#333333", fg = "#7aa9ae" })
hi(0, "lualine_b_replace", { bg = "#232323", fg = "#c48b6d" })
hi(0, "lualine_b_visual", { bg = "#232323", fg = "#7497b2" })
hi(0, "lualine_c_inactive", { bg = "#191919", fg = "#d8bb7e" })
hi(0, "lualine_c_normal", { bg = "#333333", fg = "#c3cdb2" })
hi(0, "lualine_transitional_lualine_a_command_to_lualine_b_command", { bg = "#232323", fg = "#d5695c" })
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_b_normal", { bg = "#333333", fg = "#7aa9ae" })
hi(0, "lualine_transitional_lualine_b_command_to_lualine_c_normal", { bg = "#333333", fg = "#1d1414" })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_c_normal", { bg = "#333333", fg = "#19273d" })
hi(0, "markdownCode", { fg = "#979764" })
hi(0, "markdownCodeBlock", { fg = "#979764" })
hi(0, "qfFileName", { link = "Directory" })
hi(0, "qfLineNr", { link = "LineNr" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#0d0c0c"
g.terminal_color_1 = "#c4746e"
g.terminal_color_2 = "#8a9a7b"
g.terminal_color_3 = "#c4b28a"
g.terminal_color_4 = "#96b38f"
g.terminal_color_5 = "#a292a3"
g.terminal_color_6 = "#8ea4a2"
g.terminal_color_7 = "#c8c093"
g.terminal_color_8 = "#a6a69c"
g.terminal_color_9 = "#e46876"
g.terminal_color_10 = "#87a987"
g.terminal_color_11 = "#e6c384"
g.terminal_color_12 = "#7fb4ca"
g.terminal_color_13 = "#938aa9"
g.terminal_color_14 = "#7aa89f"
g.terminal_color_15 = "#c5c9c5"
