-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "kanagawa-honmoku"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "Constant" })
hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@constructor", { fg = "#a6b465" })
hi(0, "@constructor.lua", { fg = "#c0746a" })
hi(0, "@exception", { bold = true, fg = "#de8300" })
hi(0, "@function.builtin", { link = "Special" })
hi(0, "@function.macro", { link = "Macro" })
hi(0, "@keyword.luap", { link = "@string.regex" })
hi(0, "@keyword.operator", { bold = true, fg = "#cda03b" })
hi(0, "@keyword.return", { fg = "#de8300", italic = true })
hi(0, "@lsp.mod.readonly", { link = "Constant" })
hi(0, "@lsp.mod.typeHint", { link = "Type" })
hi(0, "@lsp.type.builtinConstant", { link = "@constant.builtin" })
hi(0, "@lsp.type.class", { link = "Structure" })
hi(0, "@lsp.type.comment", {})
hi(0, "@lsp.type.decorator", { link = "Function" })
hi(0, "@lsp.type.enumMember", { link = "Constant" })
hi(0, "@lsp.type.function", { link = "Function" })
hi(0, "@lsp.type.macro", { link = "Macro" })
hi(0, "@lsp.type.magicFunction", { link = "@function.builtin" })
hi(0, "@lsp.type.method", { link = "@method" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.selfParameter", { link = "@variable.builtin" })
hi(0, "@lsp.type.struct", { link = "Structure" })
hi(0, "@lsp.type.type", { link = "Type" })
hi(0, "@lsp.type.typeParameter", { link = "Typedef" })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.function.builtin", { link = "@function.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.function.readonly", { bold = true, fg = "#87ab4b" })
hi(0, "@lsp.typemod.keyword.documentation", { link = "Special" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.controlFlow", { link = "@exception" })
hi(0, "@lsp.typemod.operator.injected", { link = "Operator" })
hi(0, "@lsp.typemod.string.injected", { link = "String" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "Special" })
hi(0, "@lsp.typemod.variable.global", { link = "Constant" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@lsp.typemod.variable.static", { link = "Constant" })
hi(0, "@parameter", { fg = "#d8ae98" })
hi(0, "@punctuation.bracket", { fg = "#a7b272" })
hi(0, "@punctuation.delimiter", { fg = "#a7b272" })
hi(0, "@punctuation.special", { fg = "#a6b465" })
hi(0, "@string.escape", { bold = true, fg = "#cda03b" })
hi(0, "@string.regex", { fg = "#cda03b" })
hi(0, "@symbol", { fg = "#f3bf50" })
hi(0, "@tag.attribute", { fg = "#f3bf50" })
hi(0, "@tag.delimiter", { fg = "#a7b272" })
hi(0, "@text.danger", { bg = "#9e7755", bold = true, fg = "#f1d291" })
hi(0, "@text.diff.add", { fg = "#a88420" })
hi(0, "@text.diff.delete", { fg = "#a46200" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.environment", { link = "Keyword" })
hi(0, "@text.environment.name", { link = "String" })
hi(0, "@text.literal", { link = "String" })
hi(0, "@text.math", { link = "Constant" })
hi(0, "@text.note", { bg = "#8a8a8a", bold = true, fg = "#303600" })
hi(0, "@text.quote", { link = "@parameter" })
hi(0, "@text.reference", { link = "Identifier" })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.title", { link = "Function" })
hi(0, "@text.todo", { link = "Todo" })
hi(0, "@text.uri", { link = "Underlined" })
hi(0, "@text.warning", { bg = "#d3b37c", bold = true, fg = "#303600" })
hi(0, "@variable", { fg = "#f1d291" })
hi(0, "@variable.builtin", { fg = "#d97a00", italic = true })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { bold = true, fg = "#f0ae00" })
hi(0, "Character", { link = "String" })
hi(0, "CmpCompletion", { link = "Pmenu" })
hi(0, "CmpCompletionBorder", { bg = "#313230", fg = "#475100" })
hi(0, "CmpCompletionSbar", { link = "PmenuSbar" })
hi(0, "CmpCompletionSel", { bg = "#4a4c4a" })
hi(0, "CmpCompletionThumb", { link = "PmenuThumb" })
hi(0, "CmpDocumentation", { link = "NormalFloat" })
hi(0, "CmpDocumentationBorder", { link = "FloatBorder" })
hi(0, "CmpItemAbbr", { fg = "#f1d291" })
hi(0, "CmpItemAbbrDefault", { fg = "#f1d291" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#7f6f46", strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#7f6f46" })
hi(0, "CmpItemAbbrMatch", { fg = "#87ab4b" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#f1d291" })
hi(0, "CmpItemAbbrMatchFuzzy", { link = "CmpItemAbbrMatch" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#f1d291" })
hi(0, "CmpItemKind", { fg = "#a6b465" })
hi(0, "CmpItemKindClass", { link = "Type" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColor", { fg = "#a6b465" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { link = "Constant" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { link = "@constructor" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindCopilot", { fg = "#d3a500" })
hi(0, "CmpItemKindDefault", { fg = "#a6b465" })
hi(0, "CmpItemKindEnum", { link = "Type" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { link = "Constant" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { fg = "#a6b465" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { link = "@field" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { link = "Directory" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { link = "Directory" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { link = "Type" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { link = "@keyword" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { link = "Function" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { link = "@include" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { link = "Operator" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { link = "@property" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { link = "Type" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { fg = "#a6b465" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { link = "Type" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { fg = "#f1d291" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { link = "Type" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { fg = "#a6b465" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { link = "String" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { fg = "#e0b966" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#7f6f46" })
hi(0, "CmpItemMenuDefault", { fg = "#f1d291" })
hi(0, "ColorColumn", { bg = "#2c2c2c" })
hi(0, "Comment", { fg = "#7f6f46", italic = true })
hi(0, "Conceal", { bold = true, fg = "#b2836e" })
hi(0, "Constant", { fg = "#f0ae00" })
hi(0, "CurSearch", { bg = "#4a4c4a", bold = true, fg = "#f1d291" })
hi(0, "Cursor", { bg = "#d6d6d6", fg = "#2f1a02" })
hi(0, "CursorColumn", { link = "CursorLine" })
hi(0, "CursorIM", { link = "Cursor" })
hi(0, "CursorLine", { bg = "#383838" })
hi(0, "CursorLineNr", { bg = "#2c2c2c", bold = true, fg = "#eaac00" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#f3bf50" })
hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
hi(0, "DapUIBreakpointsInfo", { fg = "#808548" })
hi(0, "DapUIBreakpointsPath", { link = "Directory" })
hi(0, "DapUIDecoration", { fg = "#714d3d" })
hi(0, "DapUIFloatBorder", { fg = "#714d3d" })
hi(0, "DapUILineNumber", { fg = "#a6b465" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#a6b465" })
hi(0, "DapUINormalNC", { bg = "#202020", fg = "#f1d291" })
hi(0, "DapUIPlayPause", { fg = "#daa301" })
hi(0, "DapUIPlayPauseNC", { bg = "#191919", fg = "#daa301" })
hi(0, "DapUIRestart", { fg = "#daa301" })
hi(0, "DapUIRestartNC", { bg = "#191919", fg = "#daa301" })
hi(0, "DapUIScope", { link = "Special" })
hi(0, "DapUISource", { fg = "#d97a00" })
hi(0, "DapUIStepBack", { fg = "#a6b465" })
hi(0, "DapUIStepBackNC", { bg = "#191919", fg = "#a6b465" })
hi(0, "DapUIStepInto", { fg = "#a6b465" })
hi(0, "DapUIStepIntoNC", { bg = "#191919", fg = "#a6b465" })
hi(0, "DapUIStepOut", { fg = "#a6b465" })
hi(0, "DapUIStepOutNC", { bg = "#191919", fg = "#a6b465" })
hi(0, "DapUIStepOver", { fg = "#a6b465" })
hi(0, "DapUIStepOverNC", { bg = "#191919", fg = "#a6b465" })
hi(0, "DapUIStop", { fg = "#b26d00" })
hi(0, "DapUIStopNC", { bg = "#191919", fg = "#b26d00" })
hi(0, "DapUIStoppedThread", { fg = "#a6b465" })
hi(0, "DapUIThread", { fg = "#f3bf50" })
hi(0, "DapUIType", { link = "Type" })
hi(0, "DapUIUnavailable", { fg = "#7f6f46" })
hi(0, "DapUIUnavailableNC", { bg = "#191919", fg = "#7f6f46" })
hi(0, "DapUIWatchesEmpty", { fg = "#b26d00" })
hi(0, "DapUIWatchesError", { fg = "#b26d00" })
hi(0, "DapUIWatchesValue", { fg = "#f3bf50" })
hi(0, "DapUIWinSelect", { bold = true, ctermfg = 14, fg = "#cde329" })
hi(0, "DashboardCenter", { fg = "#f3bf50" })
hi(0, "DashboardDesc", { fg = "#f3bf50" })
hi(0, "DashboardFooter", { fg = "#7f6f46" })
hi(0, "DashboardHeader", { fg = "#a46200" })
hi(0, "DashboardIcon", { fg = "#b2836e" })
hi(0, "DashboardKey", { fg = "#a6b465" })
hi(0, "DashboardShortCut", { fg = "#a6b465" })
hi(0, "Delimiter", { fg = "#a7b272" })
hi(0, "DiagnosticDeprecated", { sp = "#c47211", strikethrough = true })
hi(0, "DiagnosticError", { fg = "#b26d00" })
hi(0, "DiagnosticHint", { fg = "#978c40" })
hi(0, "DiagnosticInfo", { fg = "#808548" })
hi(0, "DiagnosticOk", { fg = "#daa301" })
hi(0, "DiagnosticSignError", { bg = "#2c2c2c", fg = "#b26d00" })
hi(0, "DiagnosticSignHint", { bg = "#2c2c2c", fg = "#978c40" })
hi(0, "DiagnosticSignInfo", { bg = "#2c2c2c", fg = "#808548" })
hi(0, "DiagnosticSignWarn", { bg = "#2c2c2c", fg = "#eaac00" })
hi(0, "DiagnosticUnderlineError", { sp = "#b9680e", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#8a8e6b", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#73866e", undercurl = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#f8d046", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#ecab18", undercurl = true })
hi(0, "DiagnosticWarn", { fg = "#eaac00" })
hi(0, "DiffAdd", { bg = "#313130" })
hi(0, "DiffChange", { bg = "#272727" })
hi(0, "DiffDelete", { bg = "#352c28", fg = "#a46200" })
hi(0, "DiffText", { bg = "#454545" })
hi(0, "Directory", { fg = "#87ab4b" })
hi(0, "EndOfBuffer", { fg = "#2f1a02" })
hi(0, "Error", { fg = "#b26d00" })
hi(0, "ErrorMsg", { fg = "#b26d00" })
hi(0, "Exception", { fg = "#d97a00" })
hi(0, "FloatBorder", { fg = "#714d3d" })
hi(0, "FloatTitle", { bold = true, fg = "#b2836e" })
hi(0, "FloatermBorder", { bg = "#202020", fg = "#714d3d" })
hi(0, "FoldColumn", { bg = "#2c2c2c", fg = "#714d3d" })
hi(0, "Folded", { bg = "#2c2c2c", fg = "#b2836e" })
hi(0, "Function", { fg = "#87ab4b" })
hi(0, "GitSignsAdd", { bg = "#2c2c2c", fg = "#a88420" })
hi(0, "GitSignsChange", { bg = "#2c2c2c", fg = "#e1a600" })
hi(0, "GitSignsDelete", { bg = "#2c2c2c", fg = "#a46200" })
hi(0, "Identifier", { fg = "#f3bf50" })
hi(0, "Ignore", { link = "NonText" })
hi(0, "IncSearch", { bg = "#d3b37c", fg = "#303600" })
hi(0, "IndentBlanklineChar", { fg = "#714d3d" })
hi(0, "IndentBlanklineContextChar", { fg = "#b2836e" })
hi(0, "IndentBlanklineContextStart", { sp = "#a88490", underline = true })
hi(0, "IndentBlanklineSpaceChar", { fg = "#714d3d" })
hi(0, "IndentBlanklineSpaceCharBlankline", { fg = "#714d3d" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#c0746a", italic = true })
hi(0, "LazyNormal", { bg = "#171717", fg = "#e0b966" })
hi(0, "LazyProgressTodo", { fg = "#714d3d" })
hi(0, "LineNr", { bg = "#2c2c2c", fg = "#714d3d" })
hi(0, "LspCodeLens", { fg = "#7f6f46" })
hi(0, "LspInfoBorder", { bold = true, fg = "#c0746a" })
hi(0, "LspInfoFiletype", { fg = "#a8a054" })
hi(0, "LspInfoList", { fg = "#87ab4b" })
hi(0, "LspInfoTip", { fg = "#7f6f46", italic = true })
hi(0, "LspInfoTitle", { bold = true, fg = "#87ab4b" })
hi(0, "LspReferenceRead", { link = "LspReferenceText" })
hi(0, "LspReferenceText", { bg = "#454545" })
hi(0, "LspReferenceWrite", { bg = "#454545", underline = true })
hi(0, "LspSignatureActiveParameter", { fg = "#eaac00" })
hi(0, "MasonNormal", { bg = "#171717", fg = "#e0b966" })
hi(0, "MatchParen", { bold = true, fg = "#eaac00" })
hi(0, "ModeMsg", { bold = true, fg = "#eaac00" })
hi(0, "MoreMsg", { fg = "#808548" })
hi(0, "MsgArea", { fg = "#e0b966" })
hi(0, "MsgSeparator", { bg = "#171717" })
hi(0, "NeoTreeGitAdded", { fg = "#a88420" })
hi(0, "NeoTreeGitConflict", { fg = "#b26d00" })
hi(0, "NeoTreeGitDeleted", { fg = "#a46200" })
hi(0, "NeoTreeGitModified", { fg = "#e1a600" })
hi(0, "NeoTreeGitStaged", { fg = "#a88420" })
hi(0, "NeoTreeGitUnstaged", { fg = "#e1a600" })
hi(0, "NeoTreeGitUntracked", { fg = "#e1a600" })
hi(0, "NeoTreeIndentMarker", { link = "NonText" })
hi(0, "NeoTreeModified", { link = "String" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#f3bf50" })
hi(0, "NeoTreeTabActive", { link = "TabLineSel" })
hi(0, "NeoTreeTabInactive", { link = "TabLine" })
hi(0, "NeoTreeTabSeparatorActive", { link = "NeoTreeTabActive" })
hi(0, "NeoTreeTabSeparatorInactive", { link = "NeoTreeTabInactive" })
hi(0, "NeogitDiffAddHighlight", { bg = "#313130" })
hi(0, "NeogitDiffContextHighlight", { bg = "#272727" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#352c28" })
hi(0, "NeogitHunkHeader", { fg = "#87ab4b" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#272727", fg = "#f0ae00" })
hi(0, "NeoscrollHiddenCursor", { blend = 100, reverse = true })
hi(0, "NonText", { fg = "#714d3d" })
hi(0, "Normal", { bg = "#202020", fg = "#f1d291" })
hi(0, "NormalDark", { bg = "#171717", fg = "#e0b966" })
hi(0, "NormalFloat", { fg = "#e0b966" })
hi(0, "NormalNC", { bg = "#191919", fg = "#e0b966" })
hi(0, "NotifierContent", { bg = "#202020", fg = "#f1d291" })
hi(0, "NotifierContentDim", { fg = "#7f6f46", italic = true })
hi(0, "NotifierIcon", { bold = true, fg = "#87ab4b" })
hi(0, "NotifierTitle", { bold = true, fg = "#87ab4b" })
hi(0, "NotifyBackground", { bg = "#202020" })
hi(0, "NotifyDEBUGBorder", { link = "Debug" })
hi(0, "NotifyDEBUGIcon", { link = "Debug" })
hi(0, "NotifyDEBUGTitle", { link = "Debug" })
hi(0, "NotifyERRORBorder", { link = "DiagnosticError" })
hi(0, "NotifyERRORIcon", { link = "DiagnosticError" })
hi(0, "NotifyERRORTitle", { link = "DiagnosticError" })
hi(0, "NotifyHINTBorder", { link = "DiagnosticHint" })
hi(0, "NotifyHINTIcon", { link = "DiagnosticHint" })
hi(0, "NotifyHINTTitle", { link = "DiagnosticHint" })
hi(0, "NotifyINFOBorder", { link = "DiagnosticInfo" })
hi(0, "NotifyINFOIcon", { link = "DiagnosticInfo" })
hi(0, "NotifyINFOTitle", { link = "DiagnosticInfo" })
hi(0, "NotifyTRACEBorder", { link = "Comment" })
hi(0, "NotifyTRACEIcon", { link = "Comment" })
hi(0, "NotifyTRACETitle", { link = "Comment" })
hi(0, "NotifyWARNBorder", { link = "DiagnosticWarn" })
hi(0, "NotifyWARNIcon", { link = "DiagnosticWarn" })
hi(0, "NotifyWARNTitle", { link = "DiagnosticWarn" })
hi(0, "NullLsInfoBorder", { fg = "#e0b966" })
hi(0, "NullLsInfoHeader", { bold = true, fg = "#c0746a" })
hi(0, "NullLsInfoSources", { bold = true, fg = "#87ab4b" })
hi(0, "NullLsInfoTitle", { fg = "#a8a054" })
hi(0, "Number", { fg = "#de7f36" })
hi(0, "NvimInternalError", { bg = "#a8805b", ctermbg = 9, ctermfg = 9, fg = "#bd7700" })
hi(0, "NvimTreeBookmark", { fg = "#a88420" })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#daa301" })
hi(0, "NvimTreeFolderIcon", { fg = "#8d9b58" })
hi(0, "NvimTreeGitDeleted", { fg = "#a46200" })
hi(0, "NvimTreeGitDirty", { fg = "#e1a600" })
hi(0, "NvimTreeGitMerge", { fg = "#f3bf50" })
hi(0, "NvimTreeGitNew", { fg = "#a88420" })
hi(0, "NvimTreeGitRenamed", { fg = "#c0746a" })
hi(0, "NvimTreeGitStaged", { fg = "#a88420" })
hi(0, "NvimTreeImageFile", { fg = "#d97a00" })
hi(0, "NvimTreeIndentMarker", { fg = "#8d9b58" })
hi(0, "NvimTreeLiveFilterPrefix", { bold = true, fg = "#c0746a" })
hi(0, "NvimTreeLiveFilterValue", { bold = true })
hi(0, "NvimTreeModifiedFile", { fg = "#a88420" })
hi(0, "NvimTreeOpenedFile", { fg = "#a6b465", italic = true })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#f3bf50" })
hi(0, "NvimTreeSpecialFile", { fg = "#a6b465" })
hi(0, "NvimTreeSymlink", { link = "Type" })
hi(0, "NvimTreeWindowPicker", { bg = "#1b1b1b", bold = true, fg = "#a6b465" })
hi(0, "Operator", { fg = "#cda03b" })
hi(0, "Pmenu", { bg = "#313230", fg = "#f1d291" })
hi(0, "PmenuSbar", { bg = "#313230" })
hi(0, "PmenuSel", { bg = "#4a4c4a" })
hi(0, "PmenuThumb", { bg = "#4a4c4a" })
hi(0, "PreProc", { fg = "#d97a00" })
hi(0, "Question", { link = "MoreMsg" })
hi(0, "QuickFixLine", { bg = "#2c2c2c" })
hi(0, "RedrawDebugClear", { bg = "#f9f4e8", ctermbg = 11 })
hi(0, "RedrawDebugComposed", { bg = "#746845", ctermbg = 10 })
hi(0, "RedrawDebugRecompose", { bg = "#a8805b", ctermbg = 9 })
hi(0, "Search", { bg = "#4a4c4a", fg = "#f1d291" })
hi(0, "SignColumn", { bg = "#2c2c2c", fg = "#b2836e" })
hi(0, "Special", { fg = "#a6b465" })
hi(0, "SpecialKey", { fg = "#b2836e" })
hi(0, "SpellBad", { sp = "#b9680e", undercurl = true })
hi(0, "SpellCap", { sp = "#ecab18", undercurl = true })
hi(0, "SpellLocal", { sp = "#ecab18", undercurl = true })
hi(0, "SpellRare", { sp = "#ecab18", undercurl = true })
hi(0, "Statement", { bold = true, fg = "#c0746a" })
hi(0, "StatusLine", { bg = "#171717", fg = "#e0b966" })
hi(0, "StatusLineNC", { bg = "#171717", fg = "#714d3d" })
hi(0, "String", { fg = "#daa301" })
hi(0, "Substitute", { bg = "#916b4c", fg = "#f1d291" })
hi(0, "TSPlaygroundFocus", { bg = "#313230" })
hi(0, "TSPlaygroundLang", { fg = "#daa301" })
hi(0, "TSQueryLinterError", { fg = "#b26d00" })
hi(0, "TabLine", { bg = "#171717", fg = "#b2836e" })
hi(0, "TabLineFill", { bg = "#202020" })
hi(0, "TabLineSel", { bg = "#2c2c2c", fg = "#e0b966" })
hi(0, "TelescopeBorder", { bg = "#202020", fg = "#714d3d" })
hi(0, "TelescopeMatching", {})
hi(0, "TelescopePreviewBorder", { bg = "#191919", fg = "#251600" })
hi(0, "TelescopePreviewNormal", { bg = "#191919" })
hi(0, "TelescopePromptBorder", { bg = "#2c2c2c", fg = "#3d260f" })
hi(0, "TelescopePromptNormal", { bg = "#2c2c2c" })
hi(0, "TelescopeResultsBorder", { bg = "#1b1b1b", fg = "#281800" })
hi(0, "TelescopeResultsClass", { link = "Structure" })
hi(0, "TelescopeResultsField", { link = "@field" })
hi(0, "TelescopeResultsMethod", { link = "Function" })
hi(0, "TelescopeResultsNormal", { bg = "#1b1b1b", fg = "#e0b966" })
hi(0, "TelescopeResultsStruct", { link = "Structure" })
hi(0, "TelescopeResultsVariable", { link = "@variable" })
hi(0, "TelescopeSelection", { link = "CursorLine" })
hi(0, "TelescopeSelectionCaret", { link = "CursorLineNr" })
hi(0, "TelescopeTitle", { bold = true, fg = "#b2836e" })
hi(0, "Title", { bold = true, fg = "#87ab4b" })
hi(0, "Todo", { bg = "#808080", bold = true, fg = "#303600" })
hi(0, "TreesitterContext", { link = "Folded" })
hi(0, "TreesitterContextBottom", {})
hi(0, "TreesitterContextLineNumber", { bg = "#2c2c2c", fg = "#b2836e" })
hi(0, "Type", { fg = "#a8a054" })
hi(0, "Underlined", { fg = "#a6b465", underline = true })
hi(0, "VertSplit", { link = "WinSeparator" })
hi(0, "Visual", { bg = "#313230" })
hi(0, "VisualNOS", { link = "Visual" })
hi(0, "WarningMsg", { fg = "#eaac00" })
hi(0, "Whitespace", { fg = "#714d3d" })
hi(0, "WildMenu", { link = "Pmenu" })
hi(0, "WinBar", { fg = "#e0b966" })
hi(0, "WinBarNC", { bg = "#191919", fg = "#e0b966" })
hi(0, "WinSeparator", { bg = "#191919", fg = "#231400" })
hi(0, "debugBreakpoint", { bg = "#2c2c2c", fg = "#a6b465" })
hi(0, "debugPC", { bg = "#352c28" })
hi(0, "diffAdded", { fg = "#a88420" })
hi(0, "diffChanged", { fg = "#e1a600" })
hi(0, "diffDeleted", { fg = "#a46200" })
hi(0, "diffNewFile", { fg = "#a88420" })
hi(0, "diffOldFile", { fg = "#a46200" })
hi(0, "diffRemoved", { fg = "#a46200" })
hi(0, "healthError", { fg = "#b26d00" })
hi(0, "healthSuccess", { fg = "#daa301" })
hi(0, "healthWarning", { fg = "#eaac00" })
hi(0, "lCursor", { link = "Cursor" })
hi(0, "lualine_a_command", { bg = "#aca79f", fg = "#2f1a02" })
hi(0, "lualine_a_inactive", { bg = "#171717", fg = "#e0b966" })
hi(0, "lualine_a_insert", { bg = "#bbab8e", fg = "#2f1a02" })
hi(0, "lualine_a_normal", { bg = "#9c9c9c", fg = "#231400" })
hi(0, "lualine_a_replace", { bg = "#d1b78d", fg = "#2f1a02" })
hi(0, "lualine_a_visual", { bg = "#8b8b8b", fg = "#2f1a02" })
hi(0, "lualine_b_command", { bg = "#202020", fg = "#cda03b" })
hi(0, "lualine_b_inactive", { bg = "#171717", bold = true, fg = "#e0b966" })
hi(0, "lualine_b_insert", { bg = "#202020", fg = "#daa301" })
hi(0, "lualine_b_normal", { bg = "#272727", fg = "#87ab4b" })
hi(0, "lualine_b_replace", { bg = "#202020", fg = "#f0ae00" })
hi(0, "lualine_b_visual", { bg = "#202020", fg = "#c0746a" })
hi(0, "lualine_c_inactive", { bg = "#171717", fg = "#e0b966" })
hi(0, "lualine_c_normal", { bg = "#2c2c2c", fg = "#f1d291" })
hi(0, "markdownCode", { fg = "#daa301" })
hi(0, "markdownCodeBlock", { fg = "#daa301" })
hi(0, "qfFileName", { link = "Directory" })
hi(0, "qfLineNr", { link = "LineNr" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#1c1518"
g.terminal_color_1 = "#ac5c0a"
g.terminal_color_2 = "#9c8758"
g.terminal_color_3 = "#c1a36f"
g.terminal_color_4 = "#76ac77"
g.terminal_color_5 = "#b6758c"
g.terminal_color_6 = "#8a8e6b"
g.terminal_color_7 = "#d4bb92"
g.terminal_color_8 = "#747069"
g.terminal_color_9 = "#b9680e"
g.terminal_color_10 = "#d1a654"
g.terminal_color_11 = "#e7c284"
g.terminal_color_12 = "#97b58e"
g.terminal_color_13 = "#a88490"
g.terminal_color_14 = "#9ba27e"
g.terminal_color_15 = "#e4d3b9"
